from __future__ import annotations

import os
from typing import Optional

import psycopg
from psycopg.rows import dict_row
from flask import g, current_app

# The application expects a DATABASE_URL env var, e.g.
# postgresql://review_user:STRONG_PASSWORD@100.x.y.z:5432/systrev_db
DATABASE_URL_ENV = "DATABASE_URL"


def get_db():
    """Return a per-request psycopg connection (cached on flask.g)."""
    if "db" not in g:
        dsn = current_app.config.get("DATABASE_URL") or os.environ.get(DATABASE_URL_ENV)
        if not dsn:
            raise RuntimeError(
                f"Missing database DSN. Set {DATABASE_URL_ENV} to a PostgreSQL URL."
            )
        # psycopg3 connection: keep API close to sqlite3 (conn.execute, commit, rollback)
        conn = psycopg.connect(dsn, row_factory=dict_row)
        g.db = conn
    return g.db


def close_db(e: Optional[BaseException] = None):
    db = g.pop("db", None)
    if db is not None:
        db.close()


def init_db(app):
    """Create tables/indexes if they don't exist (idempotent)."""
    dsn = app.config.get("DATABASE_URL") or os.environ.get(DATABASE_URL_ENV)
    if not dsn:
        # Don't create anything if the app isn't configured yet.
        # This keeps errors clearer during setup.
        return

    schema_statements = [
        """
        CREATE TABLE IF NOT EXISTS review (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            review_name TEXT NOT NULL,
            participants_number INTEGER NOT NULL DEFAULT 0,
            participants_name TEXT NOT NULL DEFAULT '',
            first_screening_progress INTEGER NOT NULL DEFAULT 0,
            second_screening_progress INTEGER NOT NULL DEFAULT 0,
            duplicates_removed INTEGER NOT NULL DEFAULT 0,
            two_reviewer_consensus TEXT NOT NULL DEFAULT 'yes'
        );
        """,
        """
        ALTER TABLE review
        ADD COLUMN IF NOT EXISTS two_reviewer_consensus TEXT NOT NULL DEFAULT 'yes';
        """,
        """
        CREATE TABLE IF NOT EXISTS reviewers (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_review INTEGER NOT NULL,
            reviewer_name TEXT NOT NULL,
            first_screening_contribution INTEGER NOT NULL DEFAULT 0,
            second_screening_contribution INTEGER NOT NULL DEFAULT 0,
            UNIQUE(id_review, reviewer_name),
            FOREIGN KEY (id_review) REFERENCES review(id) ON DELETE CASCADE
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS studies (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_review INTEGER NOT NULL,
            document_type TEXT,
            doi TEXT,
            title TEXT,
            authors TEXT,
            year INTEGER,
            abstract TEXT,
            source_title TEXT,
            file_name TEXT,
            file_data BYTEA,
            first_screening_included TEXT CHECK (first_screening_included IN ('yes','no','conflict') OR first_screening_included IS NULL),
            first_screening_notes TEXT,
            second_screening_included TEXT CHECK (second_screening_included IN ('yes','no','conflict') OR second_screening_included IS NULL),
            second_screening_notes TEXT,
            exclusion_reason INTEGER,
            UNIQUE(id_review, doi),
            UNIQUE(id_review, title, authors, year),
            FOREIGN KEY (id_review) REFERENCES review(id) ON DELETE CASCADE
        );
        """,
        """
        ALTER TABLE studies
        ADD COLUMN IF NOT EXISTS file_name TEXT;
        """,
        """
        ALTER TABLE studies
        ADD COLUMN IF NOT EXISTS file_data BYTEA;
        """,
        """
        CREATE TABLE IF NOT EXISTS first_screening (
            id_review INTEGER NOT NULL,
            id_reviewer INTEGER NOT NULL,
            id_study INTEGER NOT NULL,
            decision TEXT NOT NULL CHECK(decision IN ('yes','no','maybe')),
            FOREIGN KEY (id_review) REFERENCES review(id) ON DELETE CASCADE,
            FOREIGN KEY (id_reviewer) REFERENCES reviewers(id) ON DELETE CASCADE,
            FOREIGN KEY (id_study) REFERENCES studies(id) ON DELETE CASCADE
        );
        """,
        """
        ALTER TABLE first_screening
        DROP CONSTRAINT IF EXISTS first_screening_id_review_id_reviewer_id_study_key;
        """,
        """
        CREATE TABLE IF NOT EXISTS first_screening_conflicts (
            id_review INTEGER NOT NULL,
            id_reviewer INTEGER NOT NULL,
            id_study INTEGER NOT NULL,
            decision TEXT NOT NULL CHECK(decision IN ('yes','no','maybe')),
            UNIQUE(id_review, id_reviewer, id_study),
            FOREIGN KEY (id_review) REFERENCES review(id) ON DELETE CASCADE,
            FOREIGN KEY (id_reviewer) REFERENCES reviewers(id) ON DELETE CASCADE,
            FOREIGN KEY (id_study) REFERENCES studies(id) ON DELETE CASCADE
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS exclusion_reasons (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_review INTEGER NOT NULL,
            hierarchy INTEGER NOT NULL,
            reason TEXT NOT NULL,
            is_active INTEGER NOT NULL DEFAULT 1,
            UNIQUE(id_review, hierarchy),
            FOREIGN KEY (id_review) REFERENCES review(id) ON DELETE CASCADE
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS second_screening (
            id_review INTEGER NOT NULL,
            id_reviewer INTEGER NOT NULL,
            id_study INTEGER NOT NULL,
            decision TEXT NOT NULL CHECK(decision IN ('yes','no')),
            reason INTEGER,
            FOREIGN KEY (id_review) REFERENCES review(id) ON DELETE CASCADE,
            FOREIGN KEY (id_reviewer) REFERENCES reviewers(id) ON DELETE CASCADE,
            FOREIGN KEY (id_study) REFERENCES studies(id) ON DELETE CASCADE,
            FOREIGN KEY (reason) REFERENCES exclusion_reasons(id)
        );
        """,
        """
        ALTER TABLE second_screening
        DROP CONSTRAINT IF EXISTS second_screening_id_review_id_reviewer_id_study_key;
        """,
        """
        CREATE TABLE IF NOT EXISTS second_screening_conflicts (
            id_review INTEGER NOT NULL,
            id_reviewer INTEGER NOT NULL,
            id_study INTEGER NOT NULL,
            decision TEXT NOT NULL CHECK(decision IN ('yes','no')),
            reason INTEGER,
            UNIQUE(id_review, id_reviewer, id_study),
            FOREIGN KEY (id_review) REFERENCES review(id) ON DELETE CASCADE,
            FOREIGN KEY (id_reviewer) REFERENCES reviewers(id) ON DELETE CASCADE,
            FOREIGN KEY (id_study) REFERENCES studies(id) ON DELETE CASCADE,
            FOREIGN KEY (reason) REFERENCES exclusion_reasons(id)
        );
        """,
        """
        CREATE INDEX IF NOT EXISTS idx_studies_review ON studies(id_review);
        """,
        """
        CREATE INDEX IF NOT EXISTS idx_first_screening_study ON first_screening(id_review, id_study);
        """,
        """
        CREATE INDEX IF NOT EXISTS idx_second_screening_study ON second_screening(id_review, id_study);
        """,
    ]

    with psycopg.connect(dsn) as conn:
        for stmt in schema_statements:
            conn.execute(stmt)
        conn.commit()
